if (!requireNamespace("BiocManager", quietly = TRUE)) install.packages("BiocManager")
BiocManager::install("Biostrings")

library(Biostrings)


# 1. Definir a sequência de DNA (5' -> 3')
dna_seq <- DNAString("TGGGCCGCTTCCGGCAAGGGGGTCCGAAATCGAGAGCGGGGGAGAACTCCCGAGAGTTGGGAGAAGAAAGAGGGCGAAAATTCTCGGACGGATCCCCCAAGCTCCCAACAGAGGAAGAGAACAAGATAGAGGAGCCCCCACGACGCTAGCAAACCGTCGCGCACTGGGAGAGGAGTGGGCGGAAGATAGAAACGGAGACCCCGGTCCGAATGCCAATCGGCAGCAAACTCCTCTGGAGTCCTCCGGGCCGAAAGGAGAAAACTACCGGCGGAGGGTGATCCACCCGGAGTTGAACGGACAAGCCACATCCAGAGGACCCCTTCGGCGAACAGAAGACCCTGGTACCGGGAGGGAATAGCCCATAGTACAAGGGGAGATGCTAGGAGTCGGAGGAAGCCAGAACGACTGAGAAAGCAAAGAGAGCAACGGGGCTAGCCACCGGGTGTTCCATCCATGGGATCGGTGCCGAGTGAGGCTTATCCCGGGGGTGACGCCTCGGCCCTTCCTTAGCATCGGAATCCCGGGCCCCCTCCCAGGAATGGGAACAGGGGGAGATCGACCGGGGCCCGCAGGACCCGATGGAGTTCCCCCACCATCCCTTCCGGACGAAAACTGGTCCCGATAGGGGCACCCACAATAGGATGGCAAAAGGGGACTCTCGGGTCCGTCGTTCCATCCTTTTCTTACCTCGTGGCCGGCATGGCCCCAGCCTCCTCGCTGGCGCCGGCTGGGCAACGATCCGAGGGAGCTACTCCTCTCGAGAATCGGCAAATGGGGCCCCTCGCTCGTATCTCCGAGAGGAGACGAGAAGGAGGTGGATCTCCCTTTGCCATCCGAGGGAGCTACGCTCTCCTTACGGATGCCCAGGTCGGACCGCGAGGAGGTGGAGATCCCATGCCGACCCGAAGAGGAAAGGAGGACACGGACGACAAACCGTGAGTTCTATTGCCCTTTATTGTTGGGTGCACCCTGGGACCCAGTAATACCCGGGGGGAGGCGGGGTAAACCCATACTATGGGAACTGCTGGGTTCCTCGGATGTCGATCCCCTCTCCCGTTCGGGAAAAGGGGGACTCCGGAACTCCCTGCAGGCTGGGCACGAAGCCCCCACCGGGCGCTCCCCTCGGCGGGCCGTCCATTGGGTTCACACCCCCAGGTCGCGGGCCGGCTGTTCTTCTTTCTCTTTCGTCGTCATCCCTGGCCAGCCTCCGGAGTTCCTCTTCTTCCTCTTGGCTGAGGTGCTTTCCCCCTCCGGCCAGTTGCTTCTTCTTGTTCTCCAGGGCCTTCCTTCTTCTGTGGTCCCGCCTCTCCTGGTCGGTGAACCCCCTGGCCTTGGGTTTCCTCCCAGGTCCGGAATCAACCTCCATGGTTTCCTGCCTCGGCCTCTTCGCCGGGGGCGCTCCGTCTTCGTCCTTCTTCCTTCTCAACAGTCCAACGACGTTCCCTAGCCAGGGGTTCTCATCCTCAAGTTTCTTGATCTTCTTGTTGGCTCGCCGGAGATCCTTCTCGAGCTTTCGCCTGTTCTTCCTTTCCTCTACCCACTGTTCGAGGATCTCCTCTCTCTCCTTCGAGGTCAGCCTTGCGACGGTTTGGCTCATCCTGAGACCGGGGAGCTTCGACGATCTCTTATCTCTCCTAAGGAGGAAGGAGCTCTCGAACGCCCCCCCGGCTCCTCGGA")

# 2. Obter o reverso complemento
rev_comp <- reverseComplement(dna_seq)

print(rev_comp)
# Resultado: 9-letter DNAString object: CGATCGCAT

# 1. Cria a sequência de DNA
dna_seq <- rev_comp

# 2. Traduz para proteína (código genético padrão)
#prot_seq <- translate(dna_seq)

# Traduz a partir do segundo nucleotídeo (frame 2)
# translate(subseq(dna_seq, start = 2))
# Tradução dos 3 frames no sentido direto (5' -> 3')
frame1 <- translate(dna_seq)
frame2 <- translate(subseq(dna_seq, start = 2))
frame3 <- translate(subseq(dna_seq, start = 3))

# Converte para texto
frames <- c(
  Frame_1 = as.character(frame1),
  Frame_2 = as.character(frame2),
  Frame_3 = as.character(frame3)
)

encontrar_maior_gene <- function(dna_string) {
  # Gera a tradução dos 3 frames
  f1 <- as.character(translate(dna_string))
  f2 <- as.character(translate(subseq(dna_string, start = 2)))
  f3 <- as.character(translate(subseq(dna_string, start = 3)))
  
  # Extrai todas as ORFs que começam com M e terminam em *
  orfs <- c(f1, f2, f3) %>% 
    str_extract_all("M[^*]*\\*") %>% 
    unlist()
  
  if (length(orfs) == 0) return("Nenhuma ORF encontrada")
  
  # Retorna a maior proteína predita
  orfs[which.max(nchar(orfs))]
}

# Teste
encontrar_maior_gene(dna_seq)